<!-- <div class="row"> -->
<!-- 	<div class="span1">1 col</div> -->
<!-- 	<div class="span2">2 colonnes</div> -->
<!-- 	<div class="span3">3 colonnes</div> -->
<!-- 	<div class="span6">6 colonnes</div> -->
<!-- </div> -->
<!-- <div class="row"> -->
<!-- 	<div class="span12">12 colonnes</div> -->
<!-- </div> -->
<!-- <div class="row"> -->
<!-- 	<div class="span4">4 colonnes</div> -->
<!-- 	<div class="span8">8 colonnes</div> -->
<!-- </div> -->
<!-- <div class="row"> -->
<!-- 	<div class="span3">3 colonnes</div> -->
<!-- 	<div class="span3 offset6">3 colonnes</div> -->
<!-- </div> -->
<!-- <div class="row"> -->
<!-- 	<div class="span10">Niveau 1 -->
<!-- 		<div class="row"> -->
<!-- 			<div class="span5">Niveau 2</div> -->
<!-- 			<div class="span5">Niveau 2</div> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- </div> -->
<!-- <div class="container-fluid"> -->
<!-- 	<div class="row-fluid"> -->
<!-- 		<div class=span6>Niveau 1 -->
<!-- 			<div class="row-fluid"> -->
<!-- 				<div class="span4">Niveau 2</div> -->
<!-- 				<div class="span8">Niveau 2</div> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 		<div class=span6>Niveau 1 -->
<!-- 			<div class="row-fluid"> -->
<!-- 				<div class="span4">Niveau 2</div> -->
<!-- 				<div class="span4 offset4">Niveau 2</div> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- </div> -->



<div class="container">
	<div class="row">
		<div class="span6 offset6">
			<form class="form-search">
				<div class="input-append">
					<input type="text" class="search-query ">
					<button class="btn btn-primary" type="submit">Recherche</button>
				</div>
			</form>
		</div>
	</div>
<!-- 	<div class="page-header"> -->
<!-- 		<h1>Mon amour pour les tigres</h1> -->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!-- 		<div class="span12"> -->
<!-- 			<p>Je suis passionné par les <strong>tigres</strong> depuis très -->
<!-- 			longtemps. Ce site a été construit en <em>hommage à ces merveilleux -->
<!-- 			félins...</em><br> -->
<!-- 			Je fais partie de la <abbr title="Société des Amoureux des -->
<!-- 			Tigres">SAT</abbr> qui a pour but de faire connaître ces splendides -->
<!-- 			animaux. -->
<!-- 			</p> -->
<!-- 			<p> -->
<!-- 				<blockquote> -->
<!-- 					Le Tigre (Panthera tigris) est un mammifère -->
<!-- 					carnivore...<br> -->
<!-- 					<small class="pull-right">Wikipedia</small><br> -->
<!-- 				</blockquote> -->
<!-- 			</p> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!--		<div class="span2"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div>-->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!-- 		<div class="span4"> -->
<!-- 			<h5>Voici les sous-espèces des tigres :</h5> -->
<!-- 			<br/> -->
<!-- 			<ul> -->
<!-- 				<li>Tigre de Sibérie</li> -->
<!-- 				<li>Tigre de Chine méridionale</li> -->
<!-- 				<li>Tigre de Bali</li> -->
<!-- 				<li>Tigre de d'Indochine</li> -->
<!-- 				<li>Tigre de Malaisie</li> -->
<!-- 				<li>Tigre de Java</li> -->
<!-- 				<li>Tigre de Sumatra</li> -->
<!-- 				<li>Tigre du Bengale</li> -->
<!-- 				<li>Tigre de la Caspienne</li> -->
<!-- 			</ul> -->
<!-- 		</div> -->
<!--  		<div class="span8"><img src="<?php //echo $this->baseUrl('/img/1.jpg'); ?>" alt="ajouter un article" /></div> -->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!-- 		<div class="span12"> -->
<!-- 			<table class="table table-bordered table-striped table-condensed"> -->
<!-- 				<caption> -->
<!-- 					<h4>Les menaces pour les tigres</h4> -->
<!-- 				</caption> -->
<!-- 				<thead> -->
<!-- 					<tr> -->
<!-- 						<th>Lieu</th> -->
<!-- 						<th>Menace</th> -->
<!-- 					</tr> -->
<!-- 				</thead> -->
<!-- 				<tbody> -->
<!-- 					<tr> -->
<!-- 						<td>Grand Mekong</td> -->
<!-- 						<td>Demande croissante de certaines parties de l’animal -->
<!-- 						pour la médecine chinoise traditionnelle -->
<!-- 						et fragmentation des habitats du fait du développement non durable -->
<!-- 						d’infrastructures -->
<!-- 						</td> -->
<!-- 					</tr> -->
<!-- 					<tr> -->
<!-- 						<td>Île de Sumatra</td> -->
<!-- 						<td>Production d’huile de palme et de pâtes à -->
<!-- 						papiers -->
<!-- 						</td> -->
<!-- 					</tr> -->
<!-- 					<tr> -->
<!-- 						<td>Indonésie et Malaisie</td> -->
<!-- 						<td>Pâte à papier, l’huile de palme et le -->
<!-- 						caoutchouc -->
<!-- 						</td> -->
<!-- 					</tr> -->
<!-- 					<tr> -->
<!-- 						<td>États-Unis</td> -->
<!-- 						<td>Les tigres captifs représentent un danger pour les -->
<!-- 						tigres sauvages -->
<!-- 						</td> -->
<!-- 					</tr> -->
<!-- 					<tr> -->
<!-- 						<td>Europe</td> -->
<!-- 						<td>Gros appétit pour l’huile de palme</td> -->
<!-- 					</tr> -->
<!-- 					<tr> -->
<!-- 						<td>Népal</td> -->
<!-- 						<td>Commerce illégal de produits dérivés de tigres</td> -->
<!-- 					</tr> -->
<!-- 				</tbody> -->
<!-- 			</table> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!-- 		<div class="span8"> -->
<!-- 			<form class="form-horizontal well" id="formulaire"> -->
<!-- 				<fieldset> -->
<!-- 					<legend>Si vous voulez me laisser un message</legend> -->
<!-- 					<h4>Comment m'avez-vous trouvé ?</h4> -->
<!-- 					<br/> -->
<!-- 					<label for="ami" class="radio"> -->
<!-- 					<input type="radio" name="origine" value="ami" id="ami" />Par un ami </label> -->
					
<!-- 					<label for="web" class="radio"> -->
<!-- 					<input type="radio" name="origine" value="web" id="web" />Sur le web </label> -->
					
<!-- 					<label for="hasard" class="radio"> -->
<!-- 					<input type="radio" name="origine" value="hasard" id="hasard"/>Par hasard </label> -->
					
<!-- 					<label for="autre" class="radio"> -->
<!-- 					<input type="radio" name="origine" value="autre" id="autre" />Autre... </label> -->
					
<!-- 					<label class="control-label" for="textarea">Votre message :</label> -->
<!-- 					<div class="controls"> -->
<!-- 						<textarea id="textarea" class="input-large" rows="3"></textarea> -->
<!-- 						<p class="help-block">Vous pouvez aggrandir la fenêtre</p> -->
<!-- 					</div> -->
					
<!-- 					<button type="submit">Envoyer</button> -->
<!-- 				</fieldset> -->
<!-- 			</form> -->
<!-- 		</div> -->
<!-- 		<div class="span4"> -->
<!-- 			<address> -->
<!-- 				<p>Vous pouvez me contacter à cette adresse :</p> -->
<!-- 				<p><strong>Tigrou Alfred</strong><br> -->
<!-- 				Allée des fauves<br> -->
<!-- 				28645 Félins-sur-Loire<br> -->
<!-- 			</address> -->
<!-- 		</div> -->
<!-- 	</div> -->
<!-- 	<div class="row"> -->
<!-- 		<div class="span12"> -->
<!-- 			<form class="form-horizontal"> -->
<!-- 				<fieldset> -->
<!-- 					<legend>Validation, erreur et succès</legend> -->
<!-- 					<div class="control-group error"> -->
<!-- 						<label class="control-label" for="idError">Erreur</label> -->
<!-- 						<div class="controls"> -->
<!-- 							<input type="text" id="idError"> -->
<!-- 							<span class="help-inline">Corrigez l'erreur s'il vous plait</span>  -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 					<div class="control-group warning"> -->
<!-- 						<label class="control-label" -->
<!-- 						for="idWarning">Avertissement</label> -->
<!-- 						<div class="controls"> -->
<!-- 							<input type="text" id="idWarning"> -->
<!-- 							<span class="help-inline">Il y a un problème dans la saisie</span>  -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 					<div class="control-group success"> -->
<!-- 						<label class="control-label" for="idSuccess">Réussite</label> -->
<!-- 						<div class="controls"> -->
<!-- 							<input type="text" id="idSuccess"> -->
<!-- 							<span class="help-inline">Saisie correcte</span>  -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 				</fieldset> -->
<!-- 			</form> -->
<!-- 		</div> -->
<!-- 	</div> -->
	<div class="row">
		<div class="span5">
			<form class="form-inline well">
				<div class="control-group">
					<div class="controls">
						<input type="text" placeholder="Texte ici">
						<button type="submit" class="btn btn-primary pull-right">Envoyer</button>
						<div class="alert alert-error hide">
							<h4 class="alert-heading">Erreur !</h4>
							Vous devez entrer au moins 4 caractères ! 
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script>
	$(function()
	{
		$("form").on("submit", function()
		{
			if($("input").val().length < 4)
			{
				$("div.control-group").addClass("error");
				$("div.alert").show("slow").delay(4000).hide("slow");
				return false;
			}
		});
	});
</script>
